name: Pipeline Security Scan

on:
  workflow_call:
    outputs:
      scan-result:
        description: "Pipeline scan result"
        value: ${{ jobs.pipeline-scan.outputs.result }}

# =============================================================================
# CLAWS PIPELINE SCAN JOB
# =============================================================================
#
# Claws is a security scanner for GitHub Actions workflows
# Repository: https://github.com/Betterment/claws
#
# TO USE THIS JOB:
# 1. Copy this entire job definition into .github/workflows/pipeline-scan.yml
# 2. Replace the current jobs: definition with this one
# 3. Ensure you have a claws-config.yml file in workshop/pipeline_scan/claws/
# 4. The job will automatically scan all workflows in .github/workflows/
# =============================================================================

jobs:
  pipeline-scan:
    name: Pipeline Scan with Claws
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scan-result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set Up Ruby
        uses: ruby/setup-ruby@a16e0e66417df93dec15cb95cfb88981d4669d11
        with:
          ruby-version: '3.3'

